# This is a basic workflow to help you get started with Actions

name: AddRepos

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: "0 */7 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: main
          submodules: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sort repos by star count
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOS_URL: ${{ vars.REPOS_URL }}
        run: ruby add_repos.rb

      - name: Commit changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"
            git commit -a -m "add repos"
          else
            echo "Nothing Changes!"
          fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
